/**:
  ros__parameters:
    gait:
      knee_orientation: ">>"
      pantograph_leg: false
      odom_scaler: 0.9
      max_linear_velocity_x: 0.20 #0.50
      max_linear_velocity_y: 0.25
      max_angular_velocity_z: 1.0
      com_x_translation: 0.0
      swing_height: 0.04 #0.04
      stance_depth: 0.002 #0.00 
      stance_duration: 0.25
      nominal_height: 0.5 #0.2
    loop_rate: 50.0
    use_sim_time: true
    #added by diya 9/4
    # odom_frame: odom
    # base_link_frame: base
    base: base
    # LINKS for SPOT
    left_front_links: ["LF_HIP", "LF_THIGH", "LF_SHANK", "LF_FOOT"]
    left_hind_links: ["LH_HIP", "LH_THIGH", "LH_SHANK", "LH_FOOT"]
    right_front_links: ["RF_HIP", "RF_THIGH", "RF_SHANK", "RF_FOOT"]
    right_hind_links: ["RH_HIP", "RH_THIGH", "RH_SHANK", "RH_FOOT"]
    # JOINTS for SPOT
    left_front_joints: ["LF_HAA", "LF_HFE", "LF_KFE"]
    left_hind_joints: ["LH_HAA", "LH_HFE", "LH_KFE"]
    right_front_joints: ["RF_HAA", "RF_HFE", "RF_KFE"]
    right_hind_joints: ["RH_HAA", "RH_HFE", "RH_KFE"]

