/**:
  ros__parameters:
    gait:
      knee_orientation: ">>"
      pantograph_leg: false
      odom_scaler: 0.9
      max_linear_velocity_x: 0.20 #0.50
      max_linear_velocity_y: 0.25
      max_angular_velocity_z: 1.0
      com_x_translation: 0.0
      swing_height: 0.03 #0.04
      stance_depth: 0.002 #0.00
      stance_duration: 0.25
      nominal_height: 0.35 #0.2
    loop_rate: 50.0
    use_sim_time: true
    #added by diya 9/4
    # odom_frame: odom
    # base_link_frame: base
    base: base
    # LINKS for GO2
    left_front_links: ["LF_hip", "LF_thigh", "LF_calf", "LF_foot"]
    left_hind_links: ["LR_hip", "LR_thigh", "LR_calf", "LR_foot"]
    right_front_links: ["RF_hip", "RF_thigh", "RF_calf", "RF_foot"]
    right_hind_links: ["RR_hip", "RR_thigh", "RR_calf", "RR_foot"]
    # JOINTS for GO2
    left_front_joints: ["LF_hip_joint", "LF_upper_leg_joint", "LF_lower_leg_joint"]
    left_hind_joints: ["LR_hip_joint", "LR_upper_leg_joint", "LR_lower_leg_joint"]
    right_front_joints: ["RF_hip_joint", "RF_upper_leg_joint", "RF_lower_leg_joint"]
    right_hind_joints: ["RR_hip_joint", "RR_upper_leg_joint", "RR_lower_leg_joint"]

