- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock" 
#  lazy: true # default: false :o
  direction: GZ_TO_ROS


- ros_topic_name: "/model/go2/pose"
  gz_topic_name: "/model/go2/pose"
  ros_type_name: geometry_msgs/msg/TransformStamped # geometry_msgs/msg/TransformStamped "geometry_msgs/msg/Pose"
  gz_type_name: "gz.msgs.Pose" 
#  lazy: true
  direction: GZ_TO_ROS
  
- ros_topic_name: "/pc_d435"
  gz_topic_name: "/world/urban_circuit_02/model/go2/link/base_link/sensor/rs_d435/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked" 
#  lazy: true
  direction: GZ_TO_ROS   
  
- ros_topic_name: "/pc_d435_image"
  gz_topic_name: "/world/urban_circuit_02/model/go2/link/base_link/sensor/rs_d435/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image" 
#  lazy: true
  direction: GZ_TO_ROS     
