#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from builtin_interfaces.msg import Duration

from std_msgs.msg import String, Float64
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
from std_srvs.srv import Empty

class MoveArm(Node):

    def __init__(self):
        super().__init__('arm_node')
        self.arm_publisher_ = self.create_publisher(JointTrajectory, '/arm_trajectory_controller/joint_trajectory', 10)

        self.close_srv = self.create_service(Empty, 'close_arm', self.close_arm_callback)
        self.up_srv = self.create_service(Empty, 'up_arm', self.up_arm_callback)
        
    def close_arm_callback(self, request, response):
        traj = JointTrajectory()        

        traj = JointTrajectory()        
        traj.joint_names = ["arm_sh0", "arm_sh1", "arm_el0", "arm_el1", "arm_wr0", "arm_wr1"] #, "arm_f1x"];

        point1 = JointTrajectoryPoint()
        point1.positions = [-0.2, -0.2, 2.0, -0.2, -1.6, 0.7] #, 0.0]
        point1.time_from_start = Duration(sec=4)

        traj.points.append(point1)
        self.arm_publisher_.publish(traj)

        return response
        
    def up_arm_callback(self, request, response):
        traj = JointTrajectory()        

        traj = JointTrajectory()        
        traj.joint_names = ["arm_sh0", "arm_sh1", "arm_el0", "arm_el1", "arm_wr0", "arm_wr1"] #, "arm_f1x"];

        point1 = JointTrajectoryPoint()
        point1.positions = [0.0, -1.57, 0.0, -0.2, -1.6, 0.7] #, 0.0]
        point1.time_from_start = Duration(sec=4)

        traj.points.append(point1)
        self.arm_publisher_.publish(traj)

        return response


def main(args=None):
    rclpy.init(args=args)

    arm_node = MoveArm()

    rclpy.spin(arm_node)
    # Destroy the node explicitly
    # (optional - otherwise it will be done automatically
    # when the garbage collector destroys the node object)
    arm_node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
