#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from builtin_interfaces.msg import Duration

from std_msgs.msg import String, Float64
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
from std_srvs.srv import Empty

class MoveArm(Node):

    def __init__(self):
        super().__init__('arm_node')
        self.arm_publisher_ = self.create_publisher(JointTrajectory, '/joint_trajectory_controller/joint_trajectory', 10)
        self.open_srv = self.create_service(Empty, 'move_1', self.move_1_callback)
        self.close_srv = self.create_service(Empty, 'move_2', self.move_2_callback)
        self.random_srv = self.create_service(Empty, 'move_3', self.move_3_callback)


    def move_1_callback(self, request, response):
        traj = JointTrajectory()        
        traj.joint_names = ["front_left_hip_x", "front_left_hip_y", "front_left_knee", "rear_left_hip_x", "rear_left_hip_y", "rear_left_knee", "front_right_hip_x", "front_right_hip_y", "front_right_knee", "rear_right_hip_x", "rear_right_hip_y", "rear_right_knee"]
        
        point1 = JointTrajectoryPoint()
        point1.positions = [0.0, 0.0, -0.25, 0.0, 0.0, -0.25, 0.0, 0.0, -0.25, 0.0, 0.0, -0.25]
        point1.time_from_start = Duration(sec=4)

        traj.points.append(point1)
        self.arm_publisher_.publish(traj)

        return response


    def move_2_callback(self, request, response):
        traj = JointTrajectory()        
        traj.joint_names = ["front_left_hip_x", "front_left_hip_y", "front_left_knee", "rear_left_hip_x", "rear_left_hip_y", "rear_left_knee", "front_right_hip_x", "front_right_hip_y", "front_right_knee", "rear_right_hip_x", "rear_right_hip_y", "rear_right_knee"]
        
        point1 = JointTrajectoryPoint()
        point1.positions = [0.0, 0.0, -0.5, 0.0, 0.0, -0.5, 0.0, 0.0, -0.5, 0.0, 0.0, -0.5]
        point1.time_from_start = Duration(sec=4)

        traj.points.append(point1)
        self.arm_publisher_.publish(traj)

        return response
        
        
    def move_3_callback(self, request, response):
        traj = JointTrajectory()        
        traj.joint_names = ["front_left_hip_x", "front_left_hip_y", "front_left_knee", "rear_left_hip_x", "rear_left_hip_y", "rear_left_knee", "front_right_hip_x", "front_right_hip_y", "front_right_knee", "rear_right_hip_x", "rear_right_hip_y", "rear_right_knee"]
        
        point1 = JointTrajectoryPoint()
        point1.positions = [0.0, 0.0, -0.75, 0.0, 0.0, -0.75, 0.0, 0.0, -0.75, 0.0, 0.0, -0.75]
        point1.time_from_start = Duration(sec=4)

        traj.points.append(point1)
        self.arm_publisher_.publish(traj)

        return response


def main(args=None):
    rclpy.init(args=args)

    arm_node = MoveArm()

    rclpy.spin(arm_node)
    # Destroy the node explicitly
    # (optional - otherwise it will be done automatically
    # when the garbage collector destroys the node object)
    arm_node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
