#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from builtin_interfaces.msg import Duration

from std_msgs.msg import String, Float64
from geometry_msgs.msg import TransformStamped
from tf2_ros import TransformBroadcaster

class RepublishGround(Node):

    def __init__(self):
        super().__init__('republish_ground_truth')
        
        self.declare_parameter("fixed_frame", "world")
        self.declare_parameter("robot_frame", "body")
        self.declare_parameter("robot_pose_topic", "/model/pose/spot")
        
        self.tf_broadcaster = TransformBroadcaster(self)

    def initialize(self):
    
        self.spot_pose_topic = self.get_parameter("robot_pose_topic").get_parameter_value().string_value
        self.spot_fixed_frame = self.get_parameter("fixed_frame").get_parameter_value().string_value
        self.spot_child_frame = self.get_parameter("robot_frame").get_parameter_value().string_value
        
        self.pose_sub = self.create_subscription(TransformStamped, self.spot_pose_topic, self.pose_callback, 10)
    

    def pose_callback(self, msg):
      tfx = msg
      tfx.header.frame_id = self.spot_fixed_frame
      tfx.child_frame_id = self.spot_child_frame 

      self.tf_broadcaster.sendTransform(tfx)


def main(args=None):
    rclpy.init(args=args)

    republish_ground = RepublishGround()
    republish_ground.initialize()
    
    rclpy.spin(republish_ground)
    # Destroy the node explicitly
    # (optional - otherwise it will be done automatically
    # when the garbage collector destroys the node object)
    republish_ground.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
