#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from builtin_interfaces.msg import Duration

from std_msgs.msg import String, Float64
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
from geometry_msgs.msg import Twist
from std_srvs.srv import Empty

class SpotWalk(Node):

    def __init__(self):
        super().__init__('spot_walk_node')
        self.cmd_vel_publisher_ = self.create_publisher(Twist, '/vox_nav/cmd_vel', 10)
        self.twist = self.create_twist(0, 0, 0, 0, 0, 0)
  
        self.forward_srv = self.create_service(Empty, 'spot_forward', self.forward_callback)
        self.backward_srv = self.create_service(Empty, 'spot_backward', self.backward_callback)
        self.stop_srv = self.create_service(Empty, 'spot_stop', self.stop_callback)
        self.left_srv = self.create_service(Empty, 'spot_left', self.left_callback)
        self.right_srv = self.create_service(Empty, 'spot_right', self.right_callback)


    def create_twist(self, x, y, z, ax, ay, az):
        twist = Twist()
        twist.linear.x = x
        twist.linear.y = y
        twist.linear.z = z
        
        twist.angular.x = ax
        twist.angular.y = ay
        twist.angular.z = az

        return twist
        
    def forward_callback(self, request, response):
        self.twist = self.create_twist(0.4, 0.0, 0.0, 0.0, 0.0, 0.0)
        self.cmd_vel_publisher_.publish(self.twist)

        return response
        
    def backward_callback(self, request, response):
        self.twist = self.create_twist(-0.4, 0.0, 0.0, 0.0, 0.0, 0.0)
        self.cmd_vel_publisher_.publish(self.twist)

        return response

    def stop_callback(self, request, response):
        self.twist = self.create_twist(0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
        self.cmd_vel_publisher_.publish(self.twist)

        return response

    def left_callback(self, request, response):
        self.twist = self.create_twist(0.0, 0.0, 0.0, 0.0, 0.0, 0.3)
        self.cmd_vel_publisher_.publish(self.twist)

        return response

    def right_callback(self, request, response):
        self.twist = self.create_twist(0.0, 0.0, 0.0, 0.0, 0.0, -0.3)
        self.cmd_vel_publisher_.publish(self.twist)

        return response


def main(args=None):
    rclpy.init(args=args)

    walk_node = SpotWalk()

    rclpy.spin(walk_node)
    # Destroy the node explicitly
    # (optional - otherwise it will be done automatically
    # when the garbage collector destroys the node object)
    walk_node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
